
import { NgModule  } from '@angular/core';
import { CommonModule }  from '@angular/common';
import {
    MatToolbarModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatDatepickerModule,
    MatListModule,
    MatNativeDateModule, 
    MatCardModule,
    MatInputModule,
    MatCheckboxModule ,
    MatExpansionModule,
    MAT_CHECKBOX_CLICK_ACTION,
    MatGridListModule,
    MatSelectModule,
    MatFormFieldModule,
    MatRadioModule,
    MatTableModule,
    MatTreeModule,
    MatPaginatorModule,
    MatDialogModule 
  } from '@angular/material';
 

@NgModule({
  imports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatDatepickerModule,
    MatListModule,
    MatNativeDateModule,                              
    MatCardModule,
    MatInputModule,
    MatCheckboxModule ,
    MatExpansionModule,
    MatGridListModule,
    MatSelectModule,
    MatFormFieldModule,
    MatRadioModule,
    MatTableModule,
    MatTreeModule,
    MatPaginatorModule,
    MatButtonModule,
    MatDatepickerModule,
    MatNativeDateModule, 
    MatCardModule,
    MatInputModule,
    MatCheckboxModule ,
    MatExpansionModule,
    MatGridListModule,
    MatSelectModule,
    MatFormFieldModule,
    MatRadioModule,
    MatTableModule,
    MatTreeModule,
    MatPaginatorModule,
    MatDialogModule,
    MatButtonModule
  ],
  exports:[
    MatToolbarModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatDatepickerModule,
    MatListModule,
    MatNativeDateModule,                              
    MatCardModule,
    MatInputModule,
    MatCheckboxModule ,
    MatExpansionModule,
    MatGridListModule,
    MatSelectModule,
    MatFormFieldModule,
    MatRadioModule,
    MatTableModule,
    MatTreeModule,
    MatPaginatorModule,
    MatButtonModule,
    MatDatepickerModule,
    MatNativeDateModule, 
    MatCardModule,
    MatInputModule,
    MatCheckboxModule ,
    MatExpansionModule,
    MatGridListModule,
    MatSelectModule,
    MatFormFieldModule,
    MatRadioModule,
    MatTableModule,
    MatTreeModule,
    MatPaginatorModule,
    MatDialogModule
  ]
})
export class MaterialDesignModule {
 
}